config/routes.rb
Rails.application.routes.draw do
  resource :admin, only: :show


  resources :checks do
    get :script, on: :collection
  end

  get 'register/edit', to: 'registrants#edit'
  resources :registrants do
    post :validate_email, on: :collection
    patch :update, on: :collection
    delete :cancel, on: :collection, as: :cancel
    get '/course/:course_id', to: 'registrants#course', on: :collection, as: :course
  end

  post "/mailer"  , to: 'messages#create' , as: :mailer

  # More information on localized routes here: https://github.com/enriclluelles/route_translator
  # Actual paths in locale files, i.e. config/locales/(en|fr).yml
  localized do
    get "/team",     to: 'pages#team'
    get '/register', to: 'registrants#new'
    get '/childcare', to: 'childcare#show'
    get "/sponsors", to: 'pages#sponsors'
    get "/schedule", to: 'pages#schedule'
    get "/conduct",  to: 'pages#code_of_conduct', as: :conduct
    get "/thanks",   to: 'pages#donations_thanks'
    get "/thanks",   to: 'pages#contact'
    root to: 'pages#home'
  end

  resource :childcare, only: :register, controller: :childcare do
    post :register
  end
end

app/models/boolean_params_converter.rb
# Converts a params hash containing string representations of booleans to
# 'real' booleans.
#
class BooleanParamsConverter
  def call(params)
    convert_booleans(params)
  end

  private

  def convert_booleans(params)
    params.each do |k, v|
      params[k] = true if v == 'true'
      params[k] = false if v == 'false'
    end
  end
end

app/models/check.rb
class Check < ActiveRecord::Base
end

app/models/child.rb
class Child < ActiveRecord::Base
  validates_presence_of :name, :age
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :registrants
end

app/models/course_level_determiner.rb
# Determines the course level based on qualifying questions contained in the
# parameter hash, removing the qualifying questions from the params hash once
# completed.
#
class CourseLevelDeterminer
  def call(params)
    course = determine_course(params)
    params = remove_qualifying_params(params)
    add_course_level(params, course)
  end

  private

  def determine_course(params)
    if !params[:programmed_before]
      "beginner"
    elsif !params[:rails_before]
      "intermediate"
    else
      "advanced"
    end
  end

  def add_course_level(params, course)
    params.merge(level: course)
  end

  def remove_qualifying_params(params)
    params.reject { |key| default_qualifying_params.include? key.to_sym}
  end

  def default_qualifying_params
    %i(programmed_before ruby_before rails_before)
  end
end

app/models/edition.rb
class Edition < ActiveRecord::Base
  has_many :registrants
end

app/models/message.rb
class Message < ActiveRecord::Base
  validates :email, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  validates :message, presence: true
end

app/models/registrant.rb
class Registrant < ActiveRecord::Base

  belongs_to :course
  belongs_to :edition

  delegate :name, :room, :teachers, to: :course, prefix: true

  validates :name, presence: true
  validates :email, format: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  scope :unplaced, -> { active.where(course: nil) }
  scope :placed, -> { active.where.not(course: nil) }
  scope :active, -> { where(cancelled_at: nil, waitlisted: false) }
  scope :cancelled, -> { where.not(cancelled_at: nil) }
  scope :waitlisted, -> { where(waitlisted: true) }

  def group
    [course_name, course_room].compact.join(', ')
  end

  def teachers
    course_teachers
  end

end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  http_basic_authenticate_with name: "volunteer", password: ENV["ADMIN_PASSWORD"]
  layout 'dashboard'

  def show
    @current_edition = Edition.where(registrations_open: true).includes(:registrants).take
    @children = Child.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_registration

  def set_registration
    @waitlisting = Edition.find(2).registrants.where(cancelled_at: nil).count >= 120 || !Edition.find(2).registrations_open
  end

  protected

  def default_url_options(options={})
    { locale: I18n.locale }
  end

end

app/controllers/checks_controller.rb
class ChecksController < ApplicationController
  http_basic_authenticate_with name: "volunteer", password: ENV["ADMIN_PASSWORD"], only: :index
  skip_before_filter :verify_authenticity_token, except: :index
  before_action :find_check, only: :create
  layout :choose_layout

  def index
    @checks = Check.all.order('email ASC, created_at DESC')
  end

  def script
    render text: Rails.root.join('lib/rsvp.rb').read
  end

  def create
    if @check.save
      head :ok
    else
      head :bad_request
    end
  end

  private

    def check_params
      params.require(:check).permit(:email, :ruby_version, :ruby_platform)
    end

    def choose_layout
      "dashboard"
    end

    def find_check
      @check = Check.find_by_email(check_params[:email]) || Check.new(check_params)
    end
end

app/controllers/childcare_controller.rb
class ChildcareController < ApplicationController
  def show

  end

  def register
    @child = Child.create child_params
  end

  private

  def child_params
    params.require(:childcare).permit(:email, :name, :age, :special_needs)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  respond_to :js

  def create
    @message = Message.new(message_params)
    if @message.save
      Notifier.new_message(@message).deliver
    end
    render layout: false
  end

  private

  def message_params
    params.require(:message).permit(:email, :message)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def team
  end

  def sponsors
  end

  def schedule
  end

  def contact
  end

  def code_of_conduct
  end

  def donations_thanks
  end
end

app/controllers/registrants_controller.rb
class RegistrantsController < ApplicationController
  respond_to :js, :json

  def new
    @question_submission_method = 'post'
  end

  def edit
    @yield_in_banner = true
    @question_submission_method = 'patch'
    @email_param = params[:email]
  end

  def validate_email
    @registrant = Registrant.find_by_email(registrant_params[:email])
    render layout: false
  end

  def create
    @registrant = Register.new.register(registrant_params)
    render layout: false
  end

  def update
    @registrant = Register.new.update(params[:registrant][:id], registrant_params)
    render layout: false
  end

  def cancel
    @registrant = Registrant.find_by_email(params[:email])
    @registrant.update_attributes(cancelled_at: DateTime.now)
    render layout: false
  end

  def course
    @course = Course.find(params[:course_id])
    render json: @course.registrants.where(cancelled_at: nil).as_json(only: [:name], methods: [:group, :teachers])
  end

  private
    def registrant_params
      params.require(:registrant).permit(
        :name,
        :email,
        :bringing_laptop,
        :rails_before,
        :programmed_before,
        :ruby_before,
        :rails_before,
        :special_needs,
        :language,
        :waitlisted
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def icon_tag icon
    content_tag :i, nil, class: "fa fa-#{icon}"
  end

  def production_website?
    /railsbridge-montreal\.com/ === request.host
  end

  def eventbrite_url
    'http://railsbridgemtl-nov2013-es2.eventbrite.ca/'
  end

  def locale_switcher
    if I18n.locale.to_s == 'fr'
      locale_url = url_for params.merge(locale: 'en')
    else
      locale_url = url_for params.merge(locale: 'fr')
    end
    link_to I18n.t('locale_switcher.label'), locale_url
  end

end

app/helpers/team_helper.rb
module TeamHelper

  def team_member_tag args={}, &block
    args[:bio] = capture(&block) if block_given?
    TeamMemberPresenter.new(self, args)
  end

end

app/views/admins/_registrant_list.html.erb
  <table class="table table-striped">
    <thead>
      <tr>
        <th>id</th>
        <th>name</th>
        <th>email</th>
        <th>bringing_laptop</th>
        <th>special_needs</th>
        <th>level</th>
        <th>language</th>
        <th>cancelled_at</th>
        <th>created_at</th>
        <th>updated_at</th>
      </tr>
    </thead>
    <tbody>
      <% list.order(:id).each do |registrant| %>
        <tr>
          <td><%= registrant.id %>              </td>
          <td><%= registrant.name %>            </td>
          <td><%= registrant.email %>           </td>
          <td><%= registrant.bringing_laptop %> </td>
          <td><%= registrant.special_needs %>   </td>
          <td><%= registrant.level %>           </td>
          <td><%= registrant.language %>        </td>
          <td><%= registrant.cancelled_at&.to_formatted_s(:short) %>    </td>
          <td><%= registrant.created_at.to_formatted_s(:short) %>      </td>
          <td><%= registrant.updated_at.to_formatted_s(:short) %>      </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/checks/_check.html.erb
<tr>
  <td><%= check.email %></td>
  <td><%= check.ruby_version %></td>
  <td><%= check.ruby_platform %></td>
  <td><%= check.created_at %></td>
</tr>

app/views/checks/index.html.erb
<h1>Checks</h1>

<table>
  <%= render @checks %>
</table>

app/views/childcare/register.js.erb
<% if @child.valid? %>
  $('#add_children :input').filter(function(){ return this.value == '<%= @child.name %>' }).closest('.child-form').replaceWith('<%= simple_format t('.registered', name: @child.name) %>');
  $('.error-messages').html('');
<% else %>
  $('.error-messages').html("<div class='registration-message'><%= @child.errors.full_messages.to_sentence %></div>");
<% end %>

app/views/childcare/show.html.erb
<div class="row">
  <div class="col-md-12">
    <p class="lead"><%= t('.intro') %></p>
  </div>
</div>


<div class="well">
  <p>
    <%= simple_form_for :registrant, url: validate_email_registrants_url, remote: true, html: {class: "form-inline edit-form", id: 'email-form' } do |f| %>
      <%= simple_format t('.email_instructions') %>
      <%= f.input :email, label: false, placeholder: t('.email') %>
      <button class="btn"><i class="fa fa-rocket"></i> <%= t('.next') %></button>
    <% end %>
  </p>

  <div id='add_children' class='hidden'>
    <div class='forms'>
    </div>
    <div class='error-messages'></div>
    <button class="btn" id='add_child_btn'><i class="fa fa-plus"></i> <%= t('.add_child') %></button>
  </div>

  <div class='hide'>
    <%= form_for :childcare, url: register_childcare_path, remote: true, html: { class: 'form-template child-form', id: '' } do |f| %>
      <%= f.hidden_field :email %>
      <%= f.text_field :name, label: false, placeholder: t('.name') %>
      <%= f.number_field :age, label: false, placeholder: t('.age') %>
      <%= f.text_field :special_needs, label: false, placeholder: t('.special_needs') %>
      <button class="btn btn-success" type="submit">
        <i class="fa fa-child"></i> <%= t('.register') %>
    </button>
  <% end %>
  </div>
</div>

app/views/messages/create.js.erb
// Clear previous errors and alerts
$('input, textarea, select').closest('.form-group').removeClass('has-error');
$('.footer-form .alert').remove();

<% if @message.valid? %>

  $('.footer-form')[0].reset();
  $('.footer-form').prepend("<div class='alert alert-success'>Thank you! Your message has been successfully delivered.</div>");

<% else %>

  <% @message.errors.each do |error, message| %>
    $('.footer-form #message_<%= error.to_s %>').closest('.form-group').addClass('has-error');
  <% end %>

  $('.footer-form').prepend("<div class='alert alert-danger'>Oups. Something went wrong.<br /><%= @message.errors.full_messages.join('. ') %></div>");

<% end %>

app/views/notifier/childcare.html.erb
<%= simple_format t('.intro', name: @registrant.name) %>

<%= simple_format t('.body') %>

<%= link_to t('.register'), childcare_url %>
<br/>
<br/>
<%= simple_format t('.sponsors') %>

<%= image_tag 'sponsors_email.png' %>

app/views/notifier/confirmation_reminder.html.erb
<p><%= t('.open')%></p>
<p><%= t('.registered')%></p>
<p><%= t('.cancel', link: register_edit_path(email: @registrant.email, only_path: false, locale: @locale)).html_safe %></p>
<p><%= t('.schedule')%></p>
<p><%= t('.close')%></p>

app/views/notifier/edit_registration.html.erb
<p>Hello! Salut!</p>

<p>Vous êtes inscrit pour RailsBridge Montreal le 23 et le 24 septembre. Pour qu'on puisse vous assigner le cours le plus approprié,
  veuillez remplir <%=link_to 'un petit questionnaire ', register_edit_path(email: @registrant.email, only_path: false, locale: 'fr') %> dès que possible.
  Le questionnaire vous donnera également l'occasion d'indiquer votre langue préferée et si vous avez d'autres besoins particuliers.
</p>

<p>Si vous ne pouvez plus participer, nous vous demandons d'annuler votre inscription sur le même lien indiqué pour céder la place à quelqu'un d'autre sur notre liste d'attente.   </p>

<p>You are registered for RailsBridge Montreal on September 23 and 24th. In order to be assigned to the most appropriate course,
  please fill out this <%= link_to 'very short questionnaire ', register_edit_path(email: @registrant.email, only_path: false) %> as soon as possible.
  The questionnaire will also provide you with the opportunity to indicate yur preferred language(s) and any special needs you might have.
</p>

<p>We also ask that you cancel your registration if you are no longer able to attend to make room for someone else on our waiting list. You can do this under the same link above.</p>

<p>Merci! Thank you!</p>

app/views/notifier/new_confirmation.en.html.erb
<p>Hi <%= @registrant.name %>,</p>
<p>You're going to RailsBridge Montreal!</p>
<p>We'll keep you in touch before the event.</p>
<p>Until then feel free to reach us at any time at <%= mail_to("info@railsbridge-montreal.com") %></p>
<p>Thanks, have a lovely day.</p>

app/views/notifier/new_message.html.erb
<p>Hi there,</p>
<p>You've got a new message on railsbridge-montreal.com from <%= @message.email %></p>
<p><%= @message.message %></p>
<p>Thanks, have a lovely day.</p>

app/views/notifier/schedule.html.erb
<p><%= t('.salutation', name: @registrant.name ) %></p>

<% if @registrant.course %>
    <p><%= t('.assigned', course: @registrant.course.name, language: @registrant.course.language, teachers: @registrant.course.teachers ).html_safe %> </p>
<% end %>

<p><%= t('.cancel', link: register_edit_path(email: @registrant.email, only_path: false, locale: @locale)).html_safe %></p>

<p><%= t('.download').html_safe %></p>

<p><%= t('.location').html_safe %></p>

<h3><%= t('.friday') %></h3>
<%= simple_format t('.schedule_friday')%>

<p><%= t('.installfest') %></p>

<% if ['beginner', 'intermediate'].include? @registrant.course %>
    <p><%= t('.foundational_skills') %>  </p>
<% end %>

<h3><%= t('.saturday') %></h3>
<%= simple_format t('.schedule_saturday')%>

<p><%= t('.code_of_conduct', link: conduct_path(only_path: false, locale: @locale)).html_safe %></p>

<p><%= t('.contact')%></p>
<p><%= t('.close')%></p>
<p>&nbsp;</p>
<hr/>
<p>&nbsp;</p>
<p><%= t('.sponsors') %></p>
<p>&nbsp;</p>
<%= image_tag('sponsors_email.png') %>

app/views/registrants/_form.html.erb
<%= simple_form_for :registrant, url: registrants_path, method: @question_submission_method, remote: true, html: {class: 'questions-form' } do |f| %>
  <%= f.hidden_field :name, id: :registrant_hidden_name %>
  <%= f.hidden_field :email, id: :registrant_hidden_email %>
  <%= f.hidden_field :waitlisted, id: :registrant_hidden_waitlisted %>
  <%= f.hidden_field :id, id: :registrant_hidden_id %>
  <fieldset id='question-1' class='hidden-fieldset'>
    <h2 class="fs-title"><%= t('.tell_us')%></h2>
    <h3 class="fs-subtitle"><%= t('.programming')%></h3>
    <%= f.input :programmed_before, label: false, as: :radio_buttons %>
  </fieldset>
  <fieldset id='question-2' class='hidden-fieldset'>
    <h2 class="fs-title"><%= t('.tell_us')%></h2>
    <h3 class="fs-subtitle"><%= t('.rails')%></h3>
    <%= f.input :rails_before, label: false, as: :radio_buttons %>
  </fieldset>
  <fieldset id='question-3' class='hidden-fieldset'>
    <h2 class="fs-title"><%= t('.tell_us')%></h2>
    <h3 class="fs-subtitle"><%= t('.laptop')%></h3>
    <%= f.input :bringing_laptop, label: false, as: :radio_buttons %>
  </fieldset>
  <fieldset id='question-4' class='hidden-fieldset'>
    <h2 class="fs-title"><%= t('.tell_us')%></h2>
    <h3 class="fs-subtitle"><%= t('.language')%></h3>
    <%= f.input :language, label: false, collection: [[t('.english'), :english], [t('.french'), :french], [t('.either'), :either]], as: :radio_buttons %>
  </fieldset>
  <fieldset id='question-5' class='hidden-fieldset'>
    <h2 class="fs-title"><%= t('.anything_else')%></h2>
    <h3 class="fs-subtitle"><%= t('.needs')%></h3>
    <%= f.input :special_needs, label: false, as: :text %>
    <%= f.submit t('.complete'), :class => "btn btn-success" %>
  </fieldset>
<% end %>

app/views/registrants/edit.html.erb
<% content_for :summary do %>
  <div class="row vertically-centered">
    <div class="col-md-12">
      <%= simple_form_for :registrant, url: validate_email_registrants_url, remote: true, html: {class: "form-inline edit-form"} do |f| %>
        <%= f.input :email, label: false, placeholder: 'email', input_html: { value: @email_param } %>

        <button class="btn btn-success" type="submit">
          <i class="fa fa-rocket"></i> <%= t('.start_questionnaire') %>
        </button>
        <%= link_to cancel_registrants_url, id: 'cancel', class:'btn btn-danger',  data: { confirmation: t('.confirm') } do %>
          <i class="fa fa-minus-circle"></i> <%= t('.cancel_action') %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/registrants/new.html.erb
<% content_for :tagline do %>
  <%= t('.title') %>
<% end %>

<% content_for :summary do %>
  <h2><%= t('.event.title') %></h2>
  <ul>
    <% t('.event.dates').each_line do |date| %>
      <li><%= date.html_safe %></li>
    <% end %>
  </ul>
<% end %>

<div class="row">
  <div class="col-md-12">
    <p class="lead">
      <%= t('.intro') %>
    </p>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <h3><%= t('.instructions') %></h3>
    <ul>
      <li><strong><%= t('.level1_name') %></strong>: <%= t('.level1_description') %> </li>
      <li><strong><%= t('.level2_name') %></strong>: <%= t('.level2_description') %></li>
      <li><strong><%= t('.level3_name') %></strong>: <%= t('.level3_description') %></li>
    </ul>

    <p><%= t('.more_levels') %></p>
  </div>

  <div class="col-md-6">
    <h3><%= t('.title') %></h3>
    <div class="well">
      <%- if @waitlisting %>
        <p><%= t('.sold_out') %></p>
      <% end %>
      <%= simple_form_for :registrant, url: registrants_path, remote: true, html: {class: "form-inline registration-form"} do |f| %>
        <%= f.input :name, label: false, placeholder: t('.name'), input_html: { data: { errormsg: t('.errors.name') } } %>
        <%= f.input :email, label: false, placeholder: t('.email'), input_html: { data: { errormsg: t('.errors.email') } } %>
        <%= f.input :waitlisted, as: :hidden, input_html: { value: @waitlisting } %>
        <button class="btn btn-success" type="submit">
          <%- if @waitlisting %>
            <i class="fa fa-rocket"></i> <%= t('.register-waitlist') %>
          <%- else %>
            <i class="fa fa-rocket"></i> <%= t('.register') %>
          <% end %>
        </button>
      <% end %>
    </div>
    <p><%= t('.general_info') %></p>
    <p><%= t('.questions') %></p>
  </div>
</div>

app/views/registrants/validate_email.js.erb
$('.registration-message').remove();
<% if @registrant and !@registrant.cancelled_at %>
  $('#registrant_hidden_id')[0].value = <%= @registrant.id %>;
  if ($('body#registrants.edit').length) {
    openQuestions();
  }
  if ($('body#childcare.show').length) {
    addChild();
  }
<% else %>
  <%# <% registration_link = j(link_to('register', new_registrant_url).gsub('"', '\'')) %>
  $('.edit-form').append("<div class='registration-message'><%= I18n.t('.registrants.email_not_found') %></div>");
<% end %>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="container">
    <div class="jumbotron">
      <div class="row registration-row">
        <div class="col-md-6">
          <h1>
            <%= content_for?(:tagline) ? yield(:tagline) : t('.tagline') %>
          </h1>
        </div>
        <div class="col-md-6">
          <% if content_for?(:summary) %>
            <%= yield(:summary) %>
          <% else %>
            <p><%= raw t('.event_description') %></p>
            <p><%= raw t('.event_date') %></p>
            <p>
              <% if @waitlisting %>
                <p><%= t('registrants.new.sold_out') %></p>
                <%= link_to register_path, class: 'btn btn-primary btn-lg' do %>
                  <i class="fa fa-rocket"></i> <%= t('registrants.new.register-waitlist') %>
                <% end %>
              <% else %>
                <%= link_to register_path, class: 'btn btn-primary btn-lg' do %>
                  <i class="fa fa-rocket"></i> <%= t('registrants.new.register') %>
                <% end %>
              <% end %>
            </p>
          <% end %>
        </div>
      </div>
      <div class="row questions-row">
        <%= render "registrants/form" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="container">
  <hr />
  <div class="sponsors">
    <h1><%= t('.sponsored_by') %></h1>

      <h3><%= t('.gold') %></h3>
      <ol class='nav'>
        <div class='row'>
        <li class="sponsor"><%= image_tag 'sponsors/shopify.png', class: 'sponsor-gold' %></li>
        <li class="sponsor"><%= image_tag 'sponsors/google.jpg', class: 'sponsor-gold' %></li>
        </div>
        <div class='row'>
        <li class="sponsor"><%= image_tag 'sponsors/ets.png', class: 'sponsor-gold' %></li>
        <li class="sponsor"><%= image_tag 'sponsors/cedille.png', class: 'sponsor-gold' %></li>
        </div>
      </ol>

      <h3><%= t('.silver') %></h3>
      <ol class='nav'>
        <div class='row'>
        <li class="sponsor"><%= image_tag 'sponsors/adgear.jpg', class: 'sponsor-silver' %></li>
        <li class="sponsor"><%= link_to image_tag('sponsors/civilcode.png',
                                                  class: 'sponsor-silver',
                                                  title: "Studio Civil Code - Tailored Business Applications",
                                                  alt: "CivilCode",
                                                  height: "52"),
                                        "http://www.civilcode.io", style: "padding-top: 4px" %></li>
        <li class="sponsor"><%= image_tag 'sponsors/github.png', class: 'sponsor-silver' %></li>
        </div>
        <div class='row'>
        <li class="sponsor"><%= image_tag 'sponsors/lightspeed.png', class: 'sponsor-silver' %></li>
        <li class="sponsor"><%= image_tag 'sponsors/vigilant_global.png', class: 'sponsor-silver' %></li>
        <li class="sponsor"><%= image_tag 'sponsors/lighthouselabs.png', class: 'sponsor-silver' %></li>
        </div>
        <div class='row'>
        <li class="sponsor"><%= image_tag 'sponsors/taxelco.png', class: 'sponsor-silver' %></li>
        </div>
      </ol>

      <!--
        <h3><%= t('.bronze') %></h3>
        <ol class='nav'>
        </ol>
      -->

  </div>
</div>

<footer id='footer'>
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <h4 class='title'><%= t('.about') %></h4>
        <p><%= raw t('.event_description') %></p>
        <p><%= raw t('.montrealrb', url: link_to('montrealrb.com', 'http://www.montrealrb.com') ) %></p>
        <hr />
        <h4 class='title'><%= t('.photos') %></h4>
        <div class="photos">
          <script type="text/javascript" src="http://www.flickr.com/badge_code_v2.gne?show_name=1&count=9&display=random&size=x&layout=h&source=user&user=120783487%40N08"></script>
        </div>
      </div>
      <div class="col-md-4">
        <h4 class='title'><%= t('.drop_us_a_line') %></h4>
        <%= simple_form_for :message, url: mailer_path, remote: true, html: {class: 'footer-form', role: 'form'} do |f| %>
          <%= f.input :email, label: false, placeholder: t('.message.email') %>
          <%= f.input :message, as: :text, label: false, placeholder: t('.message.body'), input_html: {rows: 6} %>
          <%= content_tag :button, type: "submit", class: "btn btn-success" do %>
            <%= icon_tag 'envelope' %> <%= t('.message.send') %>
          <% end %>
        <% end %>
      </div>
      <div class="col-md-4">
        <a class="twitter-timeline" href="https://twitter.com/RailsbridgeMTL" data-widget-id="397079615627202560"><%= t('.tweets.title') %></a>
        <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
      </div>
    </div>
  </div>
</footer>
<div class="copyright">
  <div class="container">
    <%= raw t(
      '.github.text',
      pull_request: link_to(t('.github.pull_request'), "https://github.com/railsbridge-montreal/railsbridge-montreal-website/"),
      create_issue: link_to(t('.github.create_issue'), "https://github.com/railsbridge-montreal/railsbridge-montreal-website/issues/new")
    ) %>
  <div class="pull-right">&copy; RailsBridge Montreal <%= Time.now.year %></div>
  </div>
</div>

app/views/shared/_header.html.erb
<header id='header'>
  <div class="container">
    <nav class="navbar navbar-default" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only"><%= t('.toggle') %></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to root_path, class: 'navbar-brand' do %>
          <%= image_tag 'logo.png', alt: 'RailsBridgeMTL', class: 'logo' %>
          RailsBridge <span class='brand-subtitle'>MTL</span>
        <% end %>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to t('.register'), register_path %> </li>
          <li><%= link_to t('.childcare'), childcare_path %> </li>
          <li><%= link_to t('.home'), root_path %></li>
          <li><%= link_to t('.schedule'), schedule_path %></li>
          <li><%= link_to t('.team'), team_path %></li>
          <li><%= link_to t('.code_of_conduct'), conduct_path %></li>
          <li><%= locale_switcher %></li>
        </ul>
      </div>
    </nav>
  </div>
</header>